<?php

use Drupal\elephant_user\Service\ActivateAccount;
use Drupal\Core\Render\BubbleableMetadata;

define("VERIFICATION_URL", "http://myelephant.xyz/activation/");

/**
 * Implements hook_token_info().
 */
function elephant_user_token_info() {
  $info = array();
  $info['tokens']['elephant_user']['elephant_user_verification'] = t('Telling drupal that you define custom token');
  return $info;
}

/**
 * Implements hook_tokens().
 */
function elephant_user_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  $simple = ['customanything'];
  if ($type == 'elephant_user') {
    foreach ($tokens as $name => $original) {
      if ($name == 'elephant_user_verification') {
        $new = $simple;
        $replacements[$original] = $new;
      }
    }
  }
  return $replacements;
}

function getAccountVerificationUrl() {
  $token_service = \Drupal::token();
  $options = ['callback' => 'elephant_mail_tokens'];
  $data = array([
    "customanything" => "Fooooo Baaaar",
  ]);
  $token_service->replace('Tokens: [elephant_user:elephant_user_verification]', $data, $options);

}

function elephant_mail_tokens($replacement, $data, $options) {
  $replacement['elephant_user:elephant_user_verification'] = "This is now replaced";

}