<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.6.6
 */

/**
 * Database `u482157177_elive`
 */

/* `u482157177_elive`.`user_profiles` */
$user_profiles = array(
  array('name' => 'otoyol3','email' => 'otoyol3@lsbu.ac.uk'),
  array('name' => 'Paul Crossley','email' => 'paul.crossley@lsbu.ac.uk'),
  array('name' => 'lucia','email' => 'lucia.otoyo@lsbu.ac.uk'),
  array('name' => 'Francis ','email' => 'babayef3@lsbu.ac.uk'),
  array('name' => 'jjw','email' => 'james.whittingham@lsbu.ac.uk'),
  array('name' => 'mebush','email' => 'martin.bush@lsbu.ac.uk'),
  array('name' => 'ytf','email' => 'fgg@lsbu.ac.uk'),
  array('name' => 'srana','email' => 'ranas10@lsbu.ac.uk'),
  array('name' => 'MO','email' => 'sarumim2@lsbu.ac.uk'),
  array('name' => 'Hanna Zuchowska','email' => 'zuchowsh@lsbu.ac.uk'),
  array('name' => 'simona','email' => 'sopagais@lsbu.ac.uk'),
  array('name' => 'Dearnna_Clinkscales','email' => 'clinkscd@lsbu.ac.uk'),
  array('name' => 'Ashleighc87','email' => 'carra7@lsbu.ac.uk'),
  array('name' => 'Sultana','email' => 'ashiqs@lsbu.ac.uk'),
  array('name' => 'cliveH','email' => 'clive.hayton@lsbu.ac.uk'),
  array('name' => 'Jeffrey.Chang','email' => 'changjl@lsbu.ac.uk'),
  array('name' => 'pmkchowdary ','email' => 'ponugubm@lsbu.ac.uk'),
  array('name' => 'renbro','email' => 'broscher@lsbu.ac.uk'),
  array('name' => 'talam1992 ','email' => 'lamt3@lsbu.ac.uk'),
  array('name' => 'EmmaK','email' => 'kellye4@lsbu.ac.uk'),
  array('name' => 'agornall','email' => 'gornalla@lsbu.ac.uk'),
  array('name' => 'burkek6','email' => 'burkek6@lsbu.ac.uk'),
  array('name' => 'Sheri ','email' => 'salucids@lsbu.ac.uk'),
  array('name' => 'Licouriceface','email' => 'farebrom@lsbu.ac.uk'),
  array('name' => 'maniraka','email' => 'maniraka@lsbu.ac.uk'),
  array('name' => 'Zsharif','email' => 'sharifz4@lsbu.ac.uk'),
  array('name' => 'ChristianRogers','email' => 'rogersc6@lsbu.ac.uk'),
  array('name' => 'Ltiranti','email' => 'tirantil@lsbu.ac.uk'),
  array('name' => 'Shay','email' => 'tehrania@lsbu.ac.uk'),
  array('name' => 'Roni','email' => 'ronia@lsbu.ac.uk'),
  array('name' => 'Jobeb','email' => 'jobeb@lsbu.ac.uk'),
  array('name' => 'Millert6','email' => 'millert6@lsbu.ac.uk'),
  array('name' => 'Salustrj','email' => 'salustrj@lsbu.ac.uk'),
  array('name' => 'Aleshavyoung','email' => 'younga17@lsbu.ac.uk'),
  array('name' => 'SamAllardyce','email' => 'cardenp@lsbu.ac.uk'),
  array('name' => 'Bella','email' => 'allaberb@lsbu.ac.uk'),
  array('name' => 'Christian B','email' => 'baezac@lsbu.ac.uk'),
  array('name' => 'Dave','email' => 'hajosd@lsbu.ac.uk'),
  array('name' => 'Jamala','email' => 'abdullj3@lsbu.ac.uk'),
  array('name' => 'Ryan ','email' => 'lemon@lsbu.ac.uk'),
  array('name' => 'mandjesy','email' => 'mandjesy@lsbu.ac.uk'),
  array('name' => 'Modeline','email' => 'sitauzem@lsbu.ac.uk'),
  array('name' => 'mohayden','email' => 'haggerm@lsbu.ac.uk'),
  array('name' => 'murgaa','email' => 'murgaa@lsbu.ac.uk'),
  array('name' => 'adurodeji','email' => 'adurotia@lsbu.ac.uk'),
  array('name' => 'Dan','email' => 'dawkind7@lsbu.ac.uk'),
  array('name' => 'Gameloki','email' => 'okig@lsbu.ac.uk'),
  array('name' => 'rahmant5','email' => 'rahmant5@lsbu.ac.uk'),
  array('name' => 'SvenjaD','email' => 'duppenbs@lsbu.ac.uk'),
  array('name' => 'Alil10','email' => 'alil10@lsbu.ac.uk'),
  array('name' => 'master19297','email' => 'pateld30@lsbu.ac.uk'),
  array('name' => 'Rahul','email' => 'aler@lsbu.ac.uk'),
  array('name' => 'Eldelby2','email' => 'eldelby2@lsbu.ac.uk'),
  array('name' => 'ayindo','email' => 'dalouba2@lsbu.ac.uk'),
  array('name' => 'Nana','email' => 'koomson2@lsbu.ac.uk'),
  array('name' => 'Maheer','email' => 'ahmem114@lsbu.ac.uk'),
  array('name' => 'Mad_inventor','email' => 'barnhamj@lsbu.ac.uk'),
  array('name' => 'Francita','email' => 'dsouzaf@lsbu.ac.uk'),
  array('name' => 'whittij2','email' => 'whittij2@lsbu.ac.uk'),
  array('name' => 'Judy Robson','email' => 'robsonj2@lsbu.ac.uk'),
  array('name' => 'crawtee','email' => 'crawtee@lsbu.ac.uk'),
  array('name' => 'Adam','email' => 'berwicka@lsbu.ac.uk'),
  array('name' => 'Rebekah','email' => 'schroder@lsbu.ac.uk'),
  array('name' => 'Bullockn','email' => 'bullockn@lsbu.ac.uk'),
  array('name' => 'Kell','email' => 'smithk23@lsbu.ac.uk'),
  array('name' => 'andres_timoteo','email' => 'roncanca@lsbu.ac.uk'),
  array('name' => 'skorekm','email' => 'skorekm@lsbu.ac.uk'),
  array('name' => 'ClaudiaVan','email' => 'vannimwc@lsbu.ac.uk'),
  array('name' => 'raymondr','email' => 'raymondr@lsbu.ac.uk'),
  array('name' => 'erskinea','email' => 'erskinea@lsbu.ac.uk'),
  array('name' => 'Gc Storino','email' => 'storinog@lsbu.ac.uk'),
  array('name' => 'Nomi','email' => 'smithn26@lsbu.ac.uk'),
  array('name' => 'Highel2','email' => 'highel2@lsbu.ac.uk'),
  array('name' => 'David','email' => 'dixond3@lsbu.ac.uk'),
  array('name' => 'Nav','email' => 'dhutin@lsbu.ac.uk'),
  array('name' => 'otoyol2','email' => 'otoyol2@lsbu.ac.uk'),
  array('name' => 'Jagpal','email' => 'rajooj@lsbu.ac.uk'),
  array('name' => 'karvayi2','email' => 'karvayi2@lsbu.ac.uk'),
  array('name' => 'Censkh','email' => '09jwater@lsbu.ac.uk'),
  array('name' => 'Krasauskas','email' => 'krasausv@lsbu.ac.uk'),
  array('name' => 'Censkh','email' => 'waterhj2@lsbu.ac.uk'),
  array('name' => 'Kirsty','email' => 'chantk2@lsbu.ac.uk'),
  array('name' => 'Captainmeg','email' => 'evansm15@lsbu.ac.uk'),
  array('name' => 'rossifed','email' => 'rossif3@lsbu.ac.uk'),
  array('name' => 'Abi','email' => 'abigail.wynn-jones@lsbu.ac.uk'),
  array('name' => 'hussenm2','email' => 'hussenm2@lsbu.ac.uk'),
  array('name' => 'Pirateraygarcia','email' => 'garciac5@lsbu.ac.uk'),
  array('name' => 'Moglet ','email' => 'janssenn@lsbu.ac.uk'),
  array('name' => 'Nicola','email' => 'hallasn@lsbu.ac.uk'),
  array('name' => 'khanf33','email' => 'farrah.khan@lsbu.ac.uk'),
  array('name' => 'Cammywg','email' => 'gutterc3@lsbu.ac.uk'),
  array('name' => 'Londonpaula','email' => 'hartwigp@lsbu.ac.uk'),
  array('name' => 'GTI','email' => 'thor.ingvarsson@lsbu.ac.uk'),
  array('name' => 'MeganDanes','email' => 'danesm@lsbu.ac.uk'),
  array('name' => 'Silky ','email' => 'alabsih@lsbu.ac.uk'),
  array('name' => 'Mauramcgivern','email' => 'mcgiverm@lsbu.ac.uk'),
  array('name' => 'Paula Gomez','email' => 'gomezsap@lsbu.ac.uk'),
  array('name' => 'Sara','email' => 'abdaless@lsbu.ac.uk'),
  array('name' => 'Salma','email' => 'mrizigas@lsbu.ac.uk'),
  array('name' => 'Katarina','email' => 'grbick@lsbu.ac.uk'),
  array('name' => 'Anudari M','email' => 'magsarja@lsbu.ac.uk'),
  array('name' => 'Nick','email' => 'stanleyn@lsbu.ac.uk'),
  array('name' => 'Sutclij2','email' => 'sutclij2@lsbu.ac.uk'),
  array('name' => 'Emy','email' => 'rakotomb@lsbu.ac.uk'),
  array('name' => 'Rebecca','email' => 'fongr@lsbu.ac.uk'),
  array('name' => 'Jalli87','email' => 'jalilvaf@lsbu.ac.uk'),
  array('name' => 'Mavi','email' => 'suardim@lsbu.ac.uk'),
  array('name' => 'Opayems2','email' => 'opayems2@lsbu.ac.uk'),
  array('name' => 'Warda','email' => 'mairajw@lsbu.ac.uk'),
  array('name' => 'Jessica ','email' => 'nguyenm6@lsbu.ac.uk'),
  array('name' => 'MichelaGhittori','email' => 'ghittorm@lsbu.ac.uk'),
  array('name' => 'Harpkaursaini','email' => 'sainih@lsbu.ac.uk'),
  array('name' => 'LenaH','email' => 'heidenl@lsbu.ac.uk'),
  array('name' => 'Castelli','email' => 'castelli@lsbu.ac.uk'),
  array('name' => 'Linh','email' => 'lep@lsbu.ac.uk'),
  array('name' => 'Suny','email' => 'suny@lsbu.ac.uk'),
  array('name' => 'Sania13994','email' => 'shaiks15@lsbu.ac.uk'),
  array('name' => 'Mike_LSBU','email' => 'schleicm@lsbu.ac.uk'),
  array('name' => 'Oliviabagander','email' => 'bagando2@lsbu.ac.uk'),
  array('name' => 'hassaa85','email' => 'hassaa85@lsbu.ac.uk'),
  array('name' => 'Atif','email' => 'saddiquh@lsbu.ac.uk'),
  array('name' => 'JUNULSB','email' => 'chanayim@lsbu.ac.uk'),
  array('name' => 'Phoebe','email' => 'raynerp@lsbu.ac.uk'),
  array('name' => 'Mahoneyr','email' => 'mahoneyr@lsbu.ac.uk'),
  array('name' => 'JamesBusby','email' => 'busbyj@lsbu.ac.uk'),
  array('name' => 'Sanchezm9','email' => 'sanchem9@lsbu.ac.uk'),
  array('name' => 'Han0404','email' => 'rogersh@lsbu.ac.uk'),
  array('name' => 'MBaker11','email' => 'bakerm11@lsbu.ac.uk'),
  array('name' => 'Yazzi','email' => 'begumy3@lsbu.ac.uk'),
  array('name' => 'Amy_k','email' => 'kershaa2@lsbu.ac.uk'),
  array('name' => 'safs ','email' => 'shafis2@lsbu.ac.uk'),
  array('name' => 'Grace','email' => 'hemsworg@lsbu.ac.uk'),
  array('name' => 'Raymonv2','email' => 'raymonv2@lsbu.ac.uk'),
  array('name' => 'wolsoncs','email' => 'wolsoncs@lsbu.ac.uk'),
  array('name' => 'emilyld09','email' => 'deadmane@lsbu.ac.uk'),
  array('name' => 'Nahels','email' => 'nahels@lsbu.ac.uk'),
  array('name' => 'enigmaticmelody','email' => 'perezd2@lsbu.ac.uk'),
  array('name' => 'gordos12','email' => 'gordos12@lsbu.ac.uk'),
  array('name' => 'Juris','email' => 'barlotsj@lsbu.ac.uk'),
  array('name' => 'Fuyen','email' => 'hyf2@lsbu.ac.uk'),
  array('name' => 'Rabs','email' => 'omerr2@lsbu.ac.uk'),
  array('name' => 'ShamJ','email' => 'jackmans@lsbu.ac.uk'),
  array('name' => 'Cocca.cs','email' => 'stornelc@lsbu.ac.uk'),
  array('name' => 'Nostagger','email' => 'abayomo4@lsbu.ac.uk'),
  array('name' => 'Tindalla','email' => 'tindalla@lsbu.ac.uk'),
  array('name' => 'corpinod','email' => 'corpinod@lsbu.ac.uk'),
  array('name' => 'Nageena','email' => 'nageena@lsbu.ac.uk'),
  array('name' => 'Upeksha','email' => 'madanayu@lsbu.ac.uk'),
  array('name' => 'Liga','email' => 'kurzemnl@lsbu.ac.uk'),
  array('name' => 'tasnim95','email' => 'sultant.5@lsbu.ac.uk'),
  array('name' => 'Michi','email' => 'ainswom2@lsbu.ac.uk'),
  array('name' => 'Chaudhry ','email' => 'akhtarc@lsbu.ac.uk'),
  array('name' => 'richardhart','email' => 'hartr2@lsbu.ac.uk'),
  array('name' => 'Nabachwa LL','email' => 'luyimbon@lsbu.ac.uk'),
  array('name' => 'Shuvo Mia','email' => 'mias@lsbu.ac.uk'),
  array('name' => 'blackoffee','email' => 'batiescv@lsbu.ac.uk'),
  array('name' => 'Nandopac','email' => 'pachecof@lsbu.ac.uk'),
  array('name' => 'Nikirozaay','email' => 'deleanyn@lsbu.ac.uk'),
  array('name' => 'Renaemae1','email' => 'boother2@lsbu.ac.uk'),
  array('name' => 'Radetunji','email' => 'adetunjr@lsbu.ac.uk'),
  array('name' => 'Naseeba','email' => 'mhearban@lsbu.ac.uk'),
  array('name' => 'keeng','email' => 'keeng@lsbu.ac.uk'),
  array('name' => 'Roulla','email' => 'benmabra@lsbu.ac.uk'),
  array('name' => 'garrawam','email' => 'garrawam@lsbu.ac.uk'),
  array('name' => 'monique','email' => 'gordom10@lsbu.ac.uk'),
  array('name' => 'younga16','email' => 'younga16@lsbu.ac.uk'),
  array('name' => 'tbekolari','email' => 'bekolart@lsbu.ac.uk'),
  array('name' => 'Uncle Jimmy','email' => 'akindurf@lsbu.ac.uk'),
  array('name' => 'Michal1','email' => 'bondosm@lsbu.ac.uk'),
  array('name' => 'suraj','email' => 'subashs@lsbu.ac.uk'),
  array('name' => 'Sohani Weeravardhana','email' => 'herathws@lsbu.ac.uk'),
  array('name' => 'Lemonation','email' => 'fernaj13@lsbu.ac.uk'),
  array('name' => 'Rezkalls','email' => 'rezkalls@lsbu.ac.uk'),
  array('name' => 'Margarita ','email' => 'raginam@lsbu.ac.uk'),
  array('name' => 'Lou2016','email' => 'smithl53@lsbu.ac.uk'),
  array('name' => 'Deans','email' => 'osaee@lsbu.ac.uk'),
  array('name' => 'Bukola Dan-musa ','email' => 'danmusao@lsbu.ac.uk'),
  array('name' => 'Saad','email' => 'sajjads@lsbu.ac.uk'),
  array('name' => 'Saad Sajjad','email' => 'sajjads2@lsbu.ac.uk'),
  array('name' => 'Otaa','email' => 'onwukao2@lsbu.ac.uk'),
  array('name' => 'Keyur','email' => 'dudhatk@lsbu.ac.uk'),
  array('name' => 'marshs10','email' => 'marshs10@lsbu.ac.uk'),
  array('name' => 'Teacys','email' => 'teacys@lsbu.ac.uk'),
  array('name' => 'Raheel96','email' => 'hussar12@lsbu.ac.uk'),
  array('name' => 'Ishen amara','email' => 'amarai@lsbu.ac.uk'),
  array('name' => 'Chloe','email' => 'kwaminc@lsbu.ac.uk'),
  array('name' => 'barnesc9','email' => 'barnesc9@lsbu.ac.uk'),
  array('name' => 'Mel C','email' => 'clarkm27@lsbu.ac.uk'),
  array('name' => 'Katherin ','email' => 'rodrigk3@lsbu.ac.uk'),
  array('name' => 'Sandy','email' => 'rochas@lsbu.ac.uk'),
  array('name' => 'Shezi','email' => 'haques10@lsbu.ac.uk'),
  array('name' => 'kogaion','email' => 'iona@lsbu.ac.uk'),
  array('name' => 'Languea','email' => 'languea@lsbu.ac.uk'),
  array('name' => 'SUNGCHULPARK','email' => 'parks9@lsbu.ac.uk'),
  array('name' => 'JCO','email' => 'owusuj10@lsbu.ac.uk'),
  array('name' => 'Francisco Jose Padillo','email' => 'padillof@lsbu.ac.uk'),
  array('name' => 'JuliaT','email' => 'troschkj@lsbu.ac.uk'),
  array('name' => 'Abiola','email' => 'akinola4@lsbu.ac.uk'),
  array('name' => 'Melbouw3','email' => 'melbouw3@lsbu.ac.uk'),
  array('name' => 'YAMA123','email' => 'kifley@lsbu.ac.uk'),
  array('name' => 'Moonsammy','email' => 'moonsami@lsbu.ac.uk'),
  array('name' => 'Emily','email' => 'vanhelme@lsbu.ac.uk'),
  array('name' => 'Glimerre ','email' => 'bykovaie@lsbu.ac.uk'),
  array('name' => 'Mbeyip','email' => 'mbeyip@lsbu.ac.uk'),
  array('name' => 'Ndc140','email' => 'clairmon@lsbu.ac.uk'),
  array('name' => 'lowel','email' => 'lowel@lsbu.ac.uk'),
  array('name' => 'mistrys5','email' => 'mistrys5@lsbu.ac.uk'),
  array('name' => 'Okerej','email' => 'okerej@lsbu.ac.uk'),
  array('name' => 'Mosesg','email' => 'mosesg@lsbu.ac.uk'),
  array('name' => 'Emma Hume ','email' => 'humee@lsbu.ac.uk'),
  array('name' => 'Chloebritt','email' => 'brittc@lsbu.ac.uk'),
  array('name' => 'klime','email' => 'klime@lsbu.ac.uk'),
  array('name' => 'Katriya ross ','email' => 'rossk4@lsbu.ac.uk'),
  array('name' => 'Carolineknelson','email' => 'nelsonc6@lsbu.ac.uk'),
  array('name' => 'Suzanne Edu','email' => 'edus2@lsbu.ac.uk'),
  array('name' => 'Rina','email' => 'malikar@lsbu.ac.uk'),
  array('name' => 'monwubau','email' => 'monwubau@lsbu.ac.uk'),
  array('name' => 'Gopalv','email' => 'gopalv@lsbu.ac.uk'),
  array('name' => 'Marshaee','email' => 'marshaee@lsbu.ac.uk'),
  array('name' => 'Perrimcj','email' => 'perrimcj@lsbu.ac.uk'),
  array('name' => 'Loanea','email' => 'loanea@lsbu.ac.uk'),
  array('name' => 'Mustafaj','email' => 'mustafaj@lsbu.ac.uk'),
  array('name' => 'Zenab','email' => 'issahakz@lsbu.ac.uk'),
  array('name' => 'Rumela','email' => 'ahmedr46@lsbu.ac.uk'),
  array('name' => 'Winthroe ','email' => 'winthroe@lsbu.ac.uk'),
  array('name' => 'Rejoice','email' => 'onyeanar@lsbu.ac.uk'),
  array('name' => 'Kelly Joshua','email' => 'joshuak2@lsbu.ac.uk'),
  array('name' => 'Hector','email' => 'levattih@lsbu.ac.uk'),
  array('name' => 'Sukaina','email' => 'jerajs@lsbu.ac.uk'),
  array('name' => 'Lamc','email' => 'lamc@lsbu.ac.uk'),
  array('name' => 'Vicky1990','email' => 'owenv@lsbu.ac.uk'),
  array('name' => 'Gabrieldowsing','email' => 'dowsingg@lsbu.ac.uk'),
  array('name' => 'Hollingd','email' => 'hollingd@lsbu.ac.uk'),
  array('name' => 'Humphrey ','email' => 'anaehobh@lsbu.ac.uk'),
  array('name' => 'Rocha','email' => 'rocha@lsbu.ac.uk'),
  array('name' => 'Fran','email' => 'ponsanuf@lsbu.ac.uk'),
  array('name' => 'wud5','email' => 'wud5@lsbu.ac.uk'),
  array('name' => 'Franciscamaria','email' => 'nunesdaf@lsbu.ac.uk'),
  array('name' => 'merolad','email' => 'merolad@lsbu.ac.uk'),
  array('name' => 'Cartera8','email' => 'cartera8@lsbu.ac.uk'),
  array('name' => 'Tommo98 ','email' => 'lindsat2@lsbu.ac.uk'),
  array('name' => 'Bepi','email' => 'ulianab@lsbu.ac.uk'),
  array('name' => 'Sazzle','email' => 'willous2@lsbu.ac.uk'),
  array('name' => 'Christinahhh','email' => 'hemmerc@lsbu.ac.uk'),
  array('name' => 'jtpilks','email' => 'pilkingj@lsbu.ac.uk'),
  array('name' => 'begumm30','email' => 'begumm30@lsbu.ac.uk'),
  array('name' => 'Kirsteen','email' => 'kirsteen.coupar@lsbu.ac.uk'),
  array('name' => 'vikwhitehouse','email' => 'whitehov@lsbu.ac.uk'),
  array('name' => 'SophieChelton','email' => 'cheltons@lsbu.ac.uk'),
  array('name' => 'Gemma','email' => 'gemma.wilson@lsbu.ac.uk'),
  array('name' => 'harrie12','email' => 'harrie12@lsbu.ac.uk'),
  array('name' => 'allanp ','email' => 'allanp@lsbu.ac.uk'),
  array('name' => 'H Adam','email' => 'adamh2@lsbu.ac.uk'),
  array('name' => 'MrJWalmsley','email' => 'walmslj2@lsbu.ac.uk'),
  array('name' => 'Jonesm35','email' => 'jonesm35@lsbu.ac.uk'),
  array('name' => 'dariuszzawisza','email' => 'zawiszad@lsbu.ac.uk'),
  array('name' => 'dunhamc','email' => 'dunhamc@lsbu.ac.uk'),
  array('name' => 'Lukefletcher','email' => 'fletchl4@lsbu.ac.uk'),
  array('name' => 'May','email' => 'tungtakm@lsbu.ac.uk'),
  array('name' => 'Shannise','email' => 'choongy@lsbu.ac.uk'),
  array('name' => 'begums97','email' => 'begums97@lsbu.ac.uk'),
  array('name' => 'Rayhan Kibria','email' => 'kibriar@lsbu.ac.uk'),
  array('name' => 'paliczae','email' => 'e.palicza@lsbu.ac.uk'),
  array('name' => 'Helio','email' => 'dorosar@lsbu.ac.uk'),
  array('name' => 'TalBird','email' => 'birdt@lsbu.ac.uk')
);
