<?php
/**
 * @file
 * elephant_stack on install tasks.
 */

/**
 * Implements hook_schema().
 */
function elephant_stack_schema() {

  // Account verification schema.
  $schema['elephant_user_verification'] = array(
    'description' => 'Stores verification codes for elephant app users.',
    'fields' => array(
      'uid' => array(
        'description' => 'The primary identifier for a user.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'code' => array(
        'description' => 'The verification code for user.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => 'NULL',
      ),
      'date' => array(
        'description' => 'The datetime when code for generated.',
        'mysql_type' => 'datetime',
      ),
    ),
    'foreign keys' => array(
      'uid' => array(
        'table' => 'users',
        'columns' => array('uid' => 'uid'),
      ),
    ),
    'primary key' => array('uid'),
  );

  // Password reset schema.
  $schema['elephant_user_password_reset'] = array(
    'description' => 'Stores password reset code for elephant app users.',
    'fields' => array(
      'uid' => array(
        'description' => 'The primary identifier for a user.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'code' => array(
        'description' => 'The reset code for user.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => 'NULL',
      ),
      'date' => array(
        'description' => 'The datetime when code for generated.',
        'mysql_type' => 'datetime',
      ),
    ),
    'foreign keys' => array(
      'uid' => array(
        'table' => 'users',
        'columns' => array('uid' => 'uid'),
      ),
    ),
    'primary key' => array('uid'),
  );

  return $schema;
}