<?php
define("MODULE_NAME", "elephant_stack");
define("VERIFICATION_URL", "http://myelephant.xyz/activation/");
define("PASSWORD_RESET_URL", "http://elephant.xyz/passreset/");

/**
 * Implements hook_mail_alter().
 */
function elephant_stack_mail_alter(&$message) {
  if ($message['id'] == 'user_register_no_approval_required') {
    $joined = implode('|||', $message['body']);
    $joined = strtr($joined, array(
      '!elephant_user_verification' => getActivationUrl()));
    $message['body'][] = explode('|||', $joined);
  }
  
  if ($message['id'] == 'user_password_reset') {
    $joined = implode('|||', $message['body']);
    $joined = strtr($joined, array(
      '!elephant_user_reset_token' => getPassResetToken()));
    $message['body'][] = explode('|||', $joined);
  }
}

/**
 * @return string | url includes user uid and verification code
 * check Drupal\elephant_user\Service\ActivateAccount
 */
function getActivationUrl() {
  $activateAccount = \Drupal::service('elephant_stack.activateaccount');
  return VERIFICATION_URL . $activateAccount->getUserUid() . "/" . $activateAccount->getUserVerification();
}

/**
 * @return string | url includes user uid and reset token
 * check Drupal\elephant_user\Service\ResetPassword
 */
function getPassResetToken() {
  $resetPassword = \Drupal::service('elephant_stack.resetpassword');
  return PASSWORD_RESET_URL . $resetPassword->getUserUid() . "/" . $resetPassword->getPassResetToken();
}